### PR TITLE
fix conditional_multipurpose_modmap and add timeout

### PR DESCRIPTION
**Pull request by 3jQQuY**
Resolving conflicts of conditional_multipurpose_modmap when switching windows.

A window switch when a key is pressed will cause an error in the key state.Use a globally unified key state for recording to solve this problem.

### CODE REVIEW

**Comment by Lenbok** [comment]
Thanks, I'll test this when I get home.

**Comment by Lenbok** [comment]
Before testing your fix, I need to reproduce the problem you encountered. I tried switching windows while holding keys using the conditional_multipurpose_modmap but cannot trigger any error. 

Can you give more details on how to produce the error (e.g. perhaps a piece of config plus steps to subsequently follow) and what the error then looks like?

**Comment by 3jQQuY** [comment]
Thank you for your reply.

I use kde, and use Meta + Shift + Q as the key to exit the program, and I use Emacs as my text editing software, and set the mapping keys specifically for it. The configuration file I use is as follows: [this](https://github.com/nlfiasel/.doom.d/blob/master/dot/xkeysnail/config.py).

The triggering scenario is that when closing any program, such as a terminal, Meta + Shift + Q will be released in Emacs, which will cause an error.

The reason is this: shift is set to a multipurpose key, but after entering Emacs, this key will be processed with Emacs's map, so the state in the modified key record will not change, that is, in the set of modified keys , It is still pressed. So the keystrokes sent will always include shift.

define_timeout is a feature defined by my last commit and can be easily commented out.

**Comment by 3jQQuY** [comment]
https://github.com/nlfiasel/xkeysnail/commit/e4aad862503039e9eac912e227fa8de6bc2002c7

In this commit, the problem was simply fixed and explained, because multipurpose only has the following two cases:
action == Action.PRESS and not key_is_down
action == Action.RELEASE and key_is_down

And the situation I described belongs to:
action == Action.RELEASE and not key_is_down

This situation is not handled very well, and if each application separately records the state of the modifier keys, when switching between the maps of different applications, similar errors will occur between the maps of different applications.

**Pull request closed without merging**
